# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            User Manual
tagline:          'A Jekyll theme'
description:      'A guide to help you figure out how to deal with people'
url:              http://usermana.ul
baseurl:          /

author:
  name:           'Nick Wolf'
  url:            https://nickwolf.com.au

paginate:         5

# Custom vars
version:          0.1
