# Setup
title:            User Manual
tagline:          'How we can support each other'
description:      'A guide to help you figure out how to deal with people'
baseurl: "/"
url: ""

author:
  name:           'Nick Wolf'
  url:            https://nickwolf.com.au

paginate:         5

# Custom vars
version:          0.1
